before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # bug-workaround for "npm install [package name] removes packages"
    # https://github.com/npm/npm/issues/17379
    # https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-379397837
    - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
branches:
    only:
    - alpha
    - beta
    - benchmark
    - cron
    - docker.base
    - docker.electron
    - docker.latest
    - docker.tmp
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pMhIOqQtfZi2endr0acGn2sbjRcONK/8dogyacUcWrC4dxVAyv2tEZRcf0186ETHeTH6xlFhC5Oxy2Cbl2yleEz7rJyQrsJlzZijM51dCdewL8EGCk5aYr61XLDW+ilTZpCCBFUWr/45AT/Wdq2gUzylV2tfrG6j301HCOAkgFg= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
